/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;


import hatedashboard.Spark;

import java.awt.*;
import java.awt.BorderLayout;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.Vector;
import javax.swing.*; 
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author jesus
 */
public class Dashboard extends javax.swing.JFrame {
       
  
    Spark sp = new Spark();
   
    /**
     * Creates new form Home
     */
    public Dashboard() {
        initComponents();
        setLocationRelativeTo(null);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        
        setReadTweets();
        setLocationTable();
        setTweetsTable();        
    }
    
    
    public void setReadTweets(){
        
        //Tweets leídos
        jLabelTweets.setText(String.valueOf(sp.getresultIdList().get(sp.getresultIdList().size()-1)));
        
    }
    
    public void setLocationTable(){
        
        DefaultTableModel locationTableModel = new DefaultTableModel();
        
        locationTableModel.addColumn("Ubicación");
        locationTableModel.addColumn("Veces de aparición");
        locationTableModel.addColumn("Porcentaje");
        
        for (String str : sp.getTweetsCount())
	  { 		      
	    
             Vector row = new Vector();
             String[] items = str.split("∥");
             row.add(items[0]); 
             row.add(items[1]); 
             row.add(items[2]); 
             locationTableModel.addRow(row);
	  }
        
        jTable1.setModel(locationTableModel);
        jScrollPane5.getViewport().add(jTable1);
     
    
    }
    
    public void setTweetsTable(){
    
        DefaultTableModel locationTableModel = new DefaultTableModel();
        
        locationTableModel.addColumn("Tweet");
        locationTableModel.addColumn("Usuario");
        locationTableModel.addColumn("Ubicación");
        
        for (int i=0; i< sp.getresultTweetList().size(); i++)
	  { 		      
             Object[] row = {sp.getresultTweetList().get(i), sp.getresultUserList().get(i), sp.getresultLocationStringList().get(i) };
             locationTableModel.addRow(row);
	  }
        
        jTable2.setModel(locationTableModel);
        jScrollPane4.getViewport().add(jTable2);
      
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeaderBG = new javax.swing.JPanel();
        jPTAnalizados = new javax.swing.JPanel();
        jLabelTweets = new javax.swing.JLabel();
        jLabelTweets1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPBody = new javax.swing.JPanel();
        jPanelPorcentaje = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelShowTweets = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jHeaderBG.setBackground(new java.awt.Color(29, 161, 242));

        jPTAnalizados.setBackground(new java.awt.Color(29, 161, 242));
        jPTAnalizados.setFocusable(false);

        jLabelTweets.setBackground(new java.awt.Color(29, 161, 242));
        jLabelTweets.setFont(new java.awt.Font("Segoe UI Semibold", 1, 80)); // NOI18N
        jLabelTweets.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTweets.setFocusable(false);

        jLabelTweets1.setBackground(new java.awt.Color(29, 161, 242));
        jLabelTweets1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabelTweets1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTweets1.setText("tweets analizados");
        jLabelTweets1.setFocusable(false);

        javax.swing.GroupLayout jPTAnalizadosLayout = new javax.swing.GroupLayout(jPTAnalizados);
        jPTAnalizados.setLayout(jPTAnalizadosLayout);
        jPTAnalizadosLayout.setHorizontalGroup(
            jPTAnalizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTAnalizadosLayout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addGroup(jPTAnalizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTweets, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTweets1))
                .addContainerGap())
        );
        jPTAnalizadosLayout.setVerticalGroup(
            jPTAnalizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTAnalizadosLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabelTweets, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTweets1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HATE SPEECH");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("detector");

        jLabel4.setText("aca aniamcion");

        javax.swing.GroupLayout jHeaderBGLayout = new javax.swing.GroupLayout(jHeaderBG);
        jHeaderBG.setLayout(jHeaderBGLayout);
        jHeaderBGLayout.setHorizontalGroup(
            jHeaderBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHeaderBGLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jHeaderBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jHeaderBGLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jHeaderBGLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(69, 69, 69)
                .addComponent(jLabel4)
                .addGap(160, 160, 160)
                .addComponent(jPTAnalizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jHeaderBGLayout.setVerticalGroup(
            jHeaderBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHeaderBGLayout.createSequentialGroup()
                .addGroup(jHeaderBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPTAnalizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jHeaderBGLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jHeaderBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jScrollPane2.setPreferredSize(new java.awt.Dimension(1400, 500));

        jPBody.setBackground(new java.awt.Color(255, 255, 255));
        jPBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPorcentaje.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPorcentaje.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "porcentaje ubicación", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(29, 161, 242))); // NOI18N

        jPanel1.setEnabled(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.setFocusable(false);
        jScrollPane5.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanelPorcentajeLayout = new javax.swing.GroupLayout(jPanelPorcentaje);
        jPanelPorcentaje.setLayout(jPanelPorcentajeLayout);
        jPanelPorcentajeLayout.setHorizontalGroup(
            jPanelPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPorcentajeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanelPorcentajeLayout.setVerticalGroup(
            jPanelPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPorcentajeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jPBody.add(jPanelPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 30, -1, -1));

        jPanelShowTweets.setBackground(new java.awt.Color(255, 255, 255));
        jPanelShowTweets.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "listado de tweets", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(29, 161, 242))); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setEnabled(false);
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout jPanelShowTweetsLayout = new javax.swing.GroupLayout(jPanelShowTweets);
        jPanelShowTweets.setLayout(jPanelShowTweetsLayout);
        jPanelShowTweetsLayout.setHorizontalGroup(
            jPanelShowTweetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowTweetsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanelShowTweetsLayout.setVerticalGroup(
            jPanelShowTweetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowTweetsLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPBody.add(jPanelShowTweets, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 541, -1, -1));

        jLabel3.setText("aca animacion");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(432, 432, 432))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPBody.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 30, 460, 493));

        jScrollPane2.setViewportView(jPBody);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jHeaderBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jHeaderBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Home().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jHeaderBG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelTweets;
    private javax.swing.JLabel jLabelTweets1;
    private javax.swing.JPanel jPBody;
    private javax.swing.JPanel jPTAnalizados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelPorcentaje;
    private javax.swing.JPanel jPanelShowTweets;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
