/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import hatedashboard.Spark;

import java.awt.BorderLayout;
import java.util.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.PieSectionLabelGenerator;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.util.Rotation;

/**
 *
 * @author jesus
 */
public class PieChart extends javax.swing.JPanel {

    /**
     * Creates new form PieChart
     */
  
    Spark sp = new Spark();

    private static final long serialVersionUID = 1L;
    
    
    public PieChart() {
        initComponents();
    }


    public PieChart(String applicationTitle, String chartTitle) {
        
        
        // This will create the dataset
        //PieDataset dataset = createDataset(listOfKeys,  listOfValues);
        PieDataset dataset = createDataset();
        // based on the dataset we create the chart
        JFreeChart chart = createChart(dataset, chartTitle);
        // we put the chart into a panel
        ChartPanel chartPanel = new ChartPanel(chart);
        // default size
        chartPanel.setPreferredSize(new java.awt.Dimension(600, 487));
        // add it to our application
        add(chartPanel, BorderLayout.CENTER);

    }
    
//    public PieChart(String applicationTitle, String chartTitle, ArrayList<String> listOfKeys, ArrayList<Long> listOfValues) {
//        
//        
//        
//        
//        // This will create the dataset
//        //PieDataset dataset = createDataset(listOfKeys,  listOfValues);
//        
//        // based on the dataset we create the chart
//        JFreeChart chart = createChart(dataset, chartTitle);
//        // we put the chart into a panel
//        ChartPanel chartPanel = new ChartPanel(chart);
//        // default size
//        chartPanel.setPreferredSize(new java.awt.Dimension(600, 470));
//        // add it to our application
//        add(chartPanel, BorderLayout.CENTER);
//
//    }
    
    
    
     private  PieDataset createDataset() {
         
        
        System.out.println("DEntro de la función!!!"+sp.getlistOfValuessAux());
         
        DefaultPieDataset result = new DefaultPieDataset();
        
        for(int i= 0; i < sp.getlistOfValuessAux().size(); i++)
        {
            result.setValue(""+i,sp.getlistOfValuessAux().get(i));
        }
        
        result.setValue("Linux", 29);
        result.setValue("Mac", 20);
        result.setValue("Windows", 51);
        result.setValue("Li", 29);
        result.setValue("Mc", 20);
        result.setValue("Wws", 51);
        result.setValue("ux", 29);
        result.setValue("ac", 20);
        result.setValue("ws", 51);
        result.setValue("ux", 29);
        result.setValue("M", 20);
        result.setValue("Wiws", 51);
        
        
        return result;

    }

//      private  PieDataset createDataset(ArrayList<String> listOfKeys, ArrayList<Long> listOfValues) {
//         
//        
//         System.out.println("DEntro de la función!!!"+sp.getlistOfValuessAux());
//         
//        DefaultPieDataset result = new DefaultPieDataset();
//        result.setValue("Linux", 29);
//        result.setValue("Mac", 20);
//        result.setValue("Windows", 51);
//        result.setValue("Li", 29);
//        result.setValue("Mc", 20);
//        result.setValue("Wws", 51);
//        result.setValue("ux", 29);
//        result.setValue("ac", 20);
//        result.setValue("ws", 51);
//        result.setValue("ux", 29);
//        result.setValue("M", 20);
//        result.setValue("Wiws", 51);
//        
//        
//        return result;
//
//    }
     
     
    /**
     * Creates a chart
     */
    private JFreeChart createChart(PieDataset dataset, String title) {

        JFreeChart chart = ChartFactory.createPieChart(
            title,                  // chart title
            dataset,                // data
            true,                   // include legend
            true,
            false
        );

        PiePlot plot = (PiePlot) chart.getPlot();
        PieSectionLabelGenerator labelGenerator = new StandardPieSectionLabelGenerator("{0} = {2}");
        plot.setLabelGenerator(labelGenerator);
//        plot.setStartAngle(290);
//        plot.setDirection(Rotation.CLOCKWISE);
//        plot.setForegroundAlpha(0.5f);
        return chart;

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
